export const COUNTRY_CURRENCY: Record<string, string> = {
  'Afghanistan': 'AFN',
  'Albania': 'ALL',
  'Algeria': 'DZD',
  'Argentina': 'ARS',
  'Armenia': 'AMD',
  'Australia': 'AUD',
  'Austria': 'EUR',
  'Azerbaijan': 'AZN',
  'Bahrain': 'BHD',
  'Bangladesh': 'BDT',
  'Belarus': 'BYN',
  'Belgium': 'EUR',
  'Brazil': 'BRL',
  'Bulgaria': 'BGN',
  'Cambodia': 'KHR',
  'Canada': 'CAD',
  'Chile': 'CLP',
  'China': 'CNY',
  'Colombia': 'COP',
  'Croatia': 'EUR',
  'Cyprus': 'EUR',
  'Czech Republic': 'CZK',
  'Denmark': 'DKK',
  'Egypt': 'EGP',
  'Estonia': 'EUR',
  'Ethiopia': 'ETB',
  'Finland': 'EUR',
  'France': 'EUR',
  'Georgia': 'GEL',
  'Germany': 'EUR',
  'Ghana': 'GHS',
  'Greece': 'EUR',
  'Hong Kong': 'HKD',
  'Hungary': 'HUF',
  'Iceland': 'ISK',
  'India': 'INR',
  'Indonesia': 'IDR',
  'Iran': 'IRR',
  'Iraq': 'IQD',
  'Ireland': 'EUR',
  'Israel': 'ILS',
  'Italy': 'EUR',
  'Japan': 'JPY',
  'Jordan': 'JOD',
  'Kazakhstan': 'KZT',
  'Kenya': 'KES',
  'Kuwait': 'KWD',
  'Latvia': 'EUR',
  'Lebanon': 'LBP',
  'Lithuania': 'EUR',
  'Luxembourg': 'EUR',
  'Malaysia': 'MYR',
  'Malta': 'EUR',
  'Mexico': 'MXN',
  'Morocco': 'MAD',
  'Myanmar': 'MMK',
  'Nepal': 'NPR',
  'Netherlands': 'EUR',
  'New Zealand': 'NZD',
  'Nigeria': 'NGN',
  'Norway': 'NOK',
  'Oman': 'OMR',
  'Pakistan': 'PKR',
  'Philippines': 'PHP',
  'Poland': 'PLN',
  'Portugal': 'EUR',
  'Qatar': 'QAR',
  'Romania': 'RON',
  'Russia': 'RUB',
  'Saudi Arabia': 'SAR',
  'Singapore': 'SGD',
  'Slovakia': 'EUR',
  'Slovenia': 'EUR',
  'South Africa': 'ZAR',
  'South Korea': 'KRW',
  'Spain': 'EUR',
  'Sri Lanka': 'LKR',
  'Sweden': 'SEK',
  'Switzerland': 'CHF',
  'Taiwan': 'TWD',
  'Thailand': 'THB',
  'Tunisia': 'TND',
  'Turkey': 'TRY',
  'Ukraine': 'UAH',
  'United Arab Emirates': 'AED',
  'United Kingdom': 'GBP',
  'United States': 'USD',
  'Vietnam': 'VND',
};

export function getCurrencyForCountry(countryName: string): string {
  return COUNTRY_CURRENCY[countryName] || 'USD';
}
